name: Update Cluster Users

on:
  schedule:
    # 15分ごとに実行
    - cron: '*/15 * * * *'
  workflow_dispatch:  # 手動実行も可能

jobs:
  update-users:
    runs-on: windows-latest

    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. PowerShellスクリプト実行
      - name: Run PowerShell script
        shell: pwsh
        run: |
          .\scripts\GetClusterPublicActiveUserCnt.ps1

      # 3. git 設定
      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 4. 変更があればコミットしてpush
      - name: Commit and push changes
        shell: pwsh
        run: |
          git add data.json
          $status = git status --porcelain
          if ($status) {
            git commit -m "Update cluster active users [skip ci]"
            git push origin main
          } else {
            Write-Host "No changes detected, skipping commit."
          }
