name: Update Cluster Active Users

on:
  schedule:
    - cron: "*/30 * * * *"  # 30分ごと
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up jq
        run: sudo apt-get install -y jq

      - name: Run script
        run: bash scripts/get_cluster_active_user_cnt.sh

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json
          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "Update data.json ($(date -u +"%Y-%m-%dT%H:%M:%SZ"))"
            git push origin main
          fi
